import "./globals.css";

export const metadata = {
  title: "property puls",
  keywords: "renta property, real estate",
  description: "Generated by Farman khan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
