import Navebar from "@/components/Navebar";
import "./globals.css";
import Footer from "@/components/Footer";
import AuthProvider from "@/components/AuthProvider";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { GlobalContextProvider } from "@/context/GlobalContext";
export const metadata = {
  title: "property puls",
  keywords: "renta property, real estate",
  description: "Generated by Farman khan",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <GlobalContextProvider>
        <html lang="en">
          <body>
            <Navebar />
            <main>{children}</main>
            <Footer />
            <ToastContainer />
          </body>
        </html>
      </GlobalContextProvider>
    </AuthProvider>
  );
}
