import Navebar from "@/components/Navebar";
import "./globals.css";
import Footer from "@/components/Footer";
import AuthProvider from "@/components/AuthProvider";

export const metadata = {
  title: "property puls",
  keywords: "renta property, real estate",
  description: "Generated by Farman khan",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body>
          <Navebar />
          {children}
          <Footer />
        </body>
      </html>
    </AuthProvider>
  );
}
